<p><span><?php echo __('Cartão de Crédito (PayPal Plus)') ?></span></p>
<p><span><b><?php echo __('Pay Id: ') ?></b><?php echo $block->getPayId() ?></span></p>
<p><span><b><?php echo __('Payer Id: ') ?></b><?php echo $block->getPayerId() ?></span></p>
<p><span><b><?php echo __('Token: ') ?></b><?php echo $block->getToken() ?></span></p>
<p><span><b><?php echo __('Installments: ') ?></b><?php echo $block->getTerm() ?></span></p>
<p><span><b><?php echo __('State PayPal: ') ?></b><?php echo $block->getStatePayPal() ?></span></p>
